[package]
name = "bthome-logger"
version = "0.1.0"
edition = "2024"
authors = ["Jakub JaneÄek"]
license = "MIT"
build = "build.rs"

[dependencies]

[build-dependencies]
vergen-gitcl = { version = "1.0.8", features = ["rustc", "cargo"] }
